name: native_camera_view
description: "A Flutter plugin for custom native camera integration. Supports image capture, camera switching, pause/resume, and unique capture of the last frame when paused on iOS & Android."
version: 0.0.17+1
homepage: https://github.com/nat0108/Native-camera-view

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - camera

flutter:

  plugin:
    platforms:
      android:
        package: com.plugin.camera_native.native_camera_view
        pluginClass: NativeCameraViewPlugin
      ios:
        pluginClass: NativeCameraViewPlugin
